# Generated by Django 4.2.4 on 2023-09-06 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('query', models.CharField(max_length=250)),
                ('technology', models.CharField(max_length=30)),
                ('file', models.FileField(upload_to='query')),
                ('comments', models.TextField()),
            ],
        ),
    ]
