# Generated by Django 4.2.4 on 2023-09-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersignup',
            name='country',
            field=models.CharField(max_length=20),
        ),
    ]
