# Generated by Django 4.2.4 on 2023-10-06 18:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_usersignup_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 6, 23, 53, 48, 925412))),
                ('cntname', models.CharField(max_length=50)),
                ('cntemail', models.EmailField(max_length=254)),
                ('cntmobile', models.BigIntegerField()),
                ('cntmessage', models.TextField()),
            ],
        ),
    ]
